[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
language = { path = "../language" }
common = { path = "../common" }
accessors = { path = "../macros/accessors"}
constructors = { path = "../macros/constructors"}