[workspace]
resolver = "3"

members = [
  "language",
  "common",
  "driver",
  "frontend",
  "middleend",
  "backend", 
  "macros/*",
]

[profile.logging]
debug-assertions = true
inherits = "release"

