[workspace]
resolver = "3"

members = [
  "language",
  "common",
  "frontend",
#   "middleend",
#   "optimizer",
#   "backend-common",
#   "backend-x86_64",
#   "backend-arm",
  "driver", "language",
]
