[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
language = { path = "../language" }
accessors = { path = "../macros/accessors"}
constructors = { path = "../macros/constructors"}