[package]
name = "driver"
version = "0.1.0"
edition = "2024"

[dependencies]
language = { path = "../language" }
common = { path = "../common" }
frontend = { path = "../frontend" }
backend = { path = "../backend" }